import sys

with open("app/services/roadmap_service.py", "r", encoding="utf-8") as f:
    original_content = f.read()

# We need to find the start of _MODULE_LOOKUP
end_idx = original_content.find("# Flat lookup for O(1) module resolution")
if end_idx == -1:
    print("Could not find _MODULE_LOOKUP in roadmap_service.py")
    sys.exit(1)

header = original_content[:original_content.find("ROADMAP_STRUCTURE: list[dict[str, Any]] = [")]
footer = original_content[end_idx:]

new_structure = """ROADMAP_STRUCTURE: list[dict[str, Any]] = [
    {
        "id": 1,
        "level_num": 1,
        "title": "TOPIK I — Level 1",
        "subtitle": "Survival Beginner",
        "color": "#10B981",
        "target_vocab": 800,
        "exam_type": "TOPIK-I",
        "pass_score": 80,
        "max_score": 200,
        "sections": [
            {"name": "Listening", "questions": 30, "time_min": 40},
            {"name": "Reading", "questions": 40, "time_min": 60},
        ],
        "xp_reward": 500,
        "modules": [
            {
                "id": "hangul-basics",
                "title": "한글 Basics",
                "icon": "📝",
                "type": "playground",
                "xp": 100,
                "description": "Master the 40 basic characters, pronunciation rules, and stroke order in the Playground.",
                "prerequisite": None,
            },
            {
                "id": "l1_vocabulary",
                "title": "Vocabulary 800",
                "icon": "📖",
                "type": "flashcard",
                "xp": 120,
                "description": "800 thematic words with romanization. Numbers, colors, family, food, etc.",
                "prerequisite": None,
            },
            {
                "id": "l1_grammar",
                "title": "Basic Grammar",
                "icon": "✏️",
                "type": "grammar_drill",
                "xp": 130,
                "description": "Basic particles + endings (이/가, 을/를, 은/는, -아요/어요).",
                "prerequisite": None,
            },
            {
                "id": "l1_listening",
                "title": "Listening",
                "icon": "🎧",
                "type": "audio_task",
                "xp": 150,
                "description": "Simple single-voice dialogues, greetings, commands, and numbers.",
                "prerequisite": None,
            },
            {
                "id": "l1_reading",
                "title": "Reading",
                "icon": "📰",
                "type": "mcq",
                "xp": 150,
                "description": "Signs, labels, and menus with visual context.",
                "prerequisite": None,
            },
            {
                "id": "l1_writing",
                "title": "Writing",
                "icon": "✍️",
                "type": "essay",
                "xp": 150,
                "description": "Trace, copy, and label tasks.",
                "prerequisite": None,
            },
            {
                "id": "l1_mock",
                "title": "Mock Exam",
                "icon": "🏆",
                "type": "mock_exam",
                "xp": 300,
                "description": "Full TOPIK-I simulation.",
                "prerequisite": None,
            },
        ],
    },
    {
        "id": 2,
        "level_num": 2,
        "title": "TOPIK I — Level 2",
        "subtitle": "Elementary",
        "color": "#3B82F6",
        "target_vocab": 1500,
        "exam_type": "TOPIK-I",
        "pass_score": 140,
        "max_score": 200,
        "sections": [
            {"name": "Listening", "questions": 30, "time_min": 40},
            {"name": "Reading", "questions": 40, "time_min": 60},
        ],
        "xp_reward": 700,
        "modules": [
            {
                "id": "l2_vocabulary",
                "title": "Vocabulary 1500",
                "icon": "📖",
                "type": "flashcard",
                "xp": 150,
                "description": "1,500 words, picture-book style.",
                "prerequisite": None,
            },
            {
                "id": "l2_grammar",
                "title": "Grammar",
                "icon": "✏️",
                "type": "grammar_drill",
                "xp": 160,
                "description": "Connectives intro (하지만, 그래서) and simple sentence chaining.",
                "prerequisite": None,
            },
            {
                "id": "l2_listening",
                "title": "Listening",
                "icon": "🎧",
                "type": "audio_task",
                "xp": 160,
                "description": "2-person dialogues.",
                "prerequisite": None,
            },
            {
                "id": "l2_reading",
                "title": "Reading",
                "icon": "📰",
                "type": "mcq",
                "xp": 160,
                "description": "Short texts, diary entries, texts.",
                "prerequisite": None,
            },
            {
                "id": "l2_writing",
                "title": "Writing",
                "icon": "✍️",
                "type": "essay",
                "xp": 160,
                "description": "Fill-in-the-blank and word cards.",
                "prerequisite": None,
            },
            {
                "id": "l2_mock",
                "title": "Mock Exam",
                "icon": "🏆",
                "type": "mock_exam",
                "xp": 400,
                "description": "TOPIK-I mock targeting 140pts.",
                "prerequisite": None,
            },
        ],
    },
    {
        "id": 3,
        "level_num": 3,
        "title": "TOPIK II — Level 3",
        "subtitle": "Intermediate",
        "color": "#F59E0B",
        "target_vocab": 3000,
        "exam_type": "TOPIK-II",
        "pass_score": 120,
        "max_score": 300,
        "sections": [
            {"name": "Writing", "questions": 4, "time_min": 70},
            {"name": "Listening", "questions": 50, "time_min": 60},
            {"name": "Reading", "questions": 50, "time_min": 70},
        ],
        "xp_reward": 900,
        "modules": [
            {
                "id": "l3_vocabulary",
                "title": "Vocabulary 3000",
                "icon": "📖",
                "type": "flashcard",
                "xp": 180,
                "description": "3,000 words, Sino-Korean roots intro.",
                "prerequisite": None,
            },
            {
                "id": "l3_grammar",
                "title": "Grammar",
                "icon": "✏️",
                "type": "grammar_drill",
                "xp": 190,
                "description": "Intermediate patterns.",
                "prerequisite": None,
            },
            {
                "id": "l3_listening",
                "title": "Listening",
                "icon": "🎧",
                "type": "audio_task",
                "xp": 180,
                "description": "Extended, multi-speaker audio.",
                "prerequisite": None,
            },
            {
                "id": "l3_reading",
                "title": "Reading",
                "icon": "📰",
                "type": "mcq",
                "xp": 180,
                "description": "Structured articles, news, brochures.",
                "prerequisite": None,
            },
            {
                "id": "l3_writing",
                "title": "Writing",
                "icon": "✍️",
                "type": "essay",
                "xp": 180,
                "description": "Paragraph writing.",
                "prerequisite": None,
            },
            {
                "id": "l3_mock",
                "title": "Mock Exam",
                "icon": "🏆",
                "type": "mock_exam",
                "xp": 500,
                "description": "TOPIK-II mock targeting 120pts.",
                "prerequisite": None,
            },
        ],
    },
    {
        "id": 4,
        "level_num": 4,
        "title": "TOPIK II — Level 4",
        "subtitle": "Upper-Intermediate",
        "color": "#8B5CF6",
        "target_vocab": 5000,
        "exam_type": "TOPIK-II",
        "pass_score": 150,
        "max_score": 300,
        "sections": [
            {"name": "Writing", "questions": 4, "time_min": 70},
            {"name": "Listening", "questions": 50, "time_min": 60},
            {"name": "Reading", "questions": 50, "time_min": 70},
        ],
        "xp_reward": 1200,
        "modules": [
            {
                "id": "l4_vocabulary",
                "title": "Vocabulary 5000",
                "icon": "📖",
                "type": "flashcard",
                "xp": 220,
                "description": "5,000 words, formal/informal pairs.",
                "prerequisite": None,
            },
            {
                "id": "l4_grammar",
                "title": "Grammar",
                "icon": "✏️",
                "type": "grammar_drill",
                "xp": 240,
                "description": "Advanced patterns + full honorifics.",
                "prerequisite": None,
            },
            {
                "id": "l4_listening",
                "title": "Listening",
                "icon": "🎧",
                "type": "audio_task",
                "xp": 220,
                "description": "Authentic dialogues.",
                "prerequisite": None,
            },
            {
                "id": "l4_reading",
                "title": "Reading",
                "icon": "📰",
                "type": "mcq",
                "xp": 220,
                "description": "Opinion pieces, reports.",
                "prerequisite": None,
            },
            {
                "id": "l4_writing",
                "title": "Writing",
                "icon": "✍️",
                "type": "essay",
                "xp": 250,
                "description": "Essay writing, TOPIK II prep.",
                "prerequisite": None,
            },
            {
                "id": "l4_mock",
                "title": "Mock Exam",
                "icon": "🏆",
                "type": "mock_exam",
                "xp": 600,
                "description": "TOPIK-II mock targeting 150pts.",
                "prerequisite": None,
            },
        ],
    },
    {
        "id": 5,
        "level_num": 5,
        "title": "TOPIK II — Level 5",
        "subtitle": "Advanced",
        "color": "#EF4444",
        "target_vocab": 8000,
        "exam_type": "TOPIK-II",
        "pass_score": 190,
        "max_score": 300,
        "sections": [
            {"name": "Writing", "questions": 4, "time_min": 70},
            {"name": "Listening", "questions": 50, "time_min": 60},
            {"name": "Reading", "questions": 50, "time_min": 70},
        ],
        "xp_reward": 1500,
        "modules": [
            {
                "id": "l5_vocabulary",
                "title": "Vocabulary 8000",
                "icon": "📖",
                "type": "flashcard",
                "xp": 300,
                "description": "8,000 words, academic register.",
                "prerequisite": None,
            },
            {
                "id": "l5_grammar",
                "title": "Grammar",
                "icon": "✏️",
                "type": "grammar_drill",
                "xp": 320,
                "description": "Complex patterns + nominalisations.",
                "prerequisite": None,
            },
            {
                "id": "l5_listening",
                "title": "Listening",
                "icon": "🎧",
                "type": "audio_task",
                "xp": 300,
                "description": "Academic lectures.",
                "prerequisite": None,
            },
            {
                "id": "l5_reading",
                "title": "Reading",
                "icon": "📰",
                "type": "mcq",
                "xp": 300,
                "description": "Academic papers, literary texts.",
                "prerequisite": None,
            },
            {
                "id": "l5_writing",
                "title": "Writing",
                "icon": "✍️",
                "type": "essay",
                "xp": 350,
                "description": "TOPIK 53 & 54 tasks.",
                "prerequisite": None,
            },
            {
                "id": "l5_mock",
                "title": "Mock Exam",
                "icon": "🏆",
                "type": "mock_exam",
                "xp": 800,
                "description": "TOPIK-II mock targeting 190pts.",
                "prerequisite": None,
            },
        ],
    },
    {
        "id": 6,
        "level_num": 6,
        "title": "TOPIK II — Level 6",
        "subtitle": "Mastery",
        "color": "#111827",
        "target_vocab": 10000,
        "exam_type": "TOPIK-II",
        "pass_score": 230,
        "max_score": 300,
        "sections": [
            {"name": "Writing", "questions": 4, "time_min": 70},
            {"name": "Listening", "questions": 50, "time_min": 60},
            {"name": "Reading", "questions": 50, "time_min": 70},
        ],
        "xp_reward": 2000,
        "modules": [
            {
                "id": "l6_vocabulary",
                "title": "Vocabulary 10000+",
                "icon": "📖",
                "type": "flashcard",
                "xp": 400,
                "description": "10,000+ words, classical Korean.",
                "prerequisite": None,
            },
            {
                "id": "l6_grammar",
                "title": "Grammar",
                "icon": "✏️",
                "type": "grammar_drill",
                "xp": 420,
                "description": "Literary + rhetorical patterns.",
                "prerequisite": None,
            },
            {
                "id": "l6_listening",
                "title": "Listening",
                "icon": "🎧",
                "type": "audio_task",
                "xp": 400,
                "description": "Debates, legal, specialist.",
                "prerequisite": None,
            },
            {
                "id": "l6_reading",
                "title": "Reading",
                "icon": "📰",
                "type": "mcq",
                "xp": 400,
                "description": "Classical, literary, critical reading.",
                "prerequisite": None,
            },
            {
                "id": "l6_writing",
                "title": "Writing",
                "icon": "✍️",
                "type": "essay",
                "xp": 500,
                "description": "Mastery essays, full TOPIK II.",
                "prerequisite": None,
            },
            {
                "id": "l6_mock",
                "title": "Mock Exam",
                "icon": "🏆",
                "type": "mock_exam",
                "xp": 1000,
                "description": "TOPIK-II mock targeting 230pts.",
                "prerequisite": None,
            },
        ],
    },
]
"""

with open("app/services/roadmap_service.py", "w", encoding="utf-8") as f:
    f.write(header + new_structure + "\n\n" + footer)

print("Updated roadmap_service.py successfully.")
